### ISSUE TITLE
Web export: TypeError: (0 , S.usePressability) is not a function

### ISSUE THREAD

**Issue by crloz** [G-Ray/expo-tamagui-universal-starter#1] opened 2023-03-07 19:30 UTC
Steps to reproduce:
1. `TAMAGUI_TARGET=web npx expo export --platform web`
2. npx serve dist
3. go to localhost:3000

```
TypeError: (0 , S.usePressability) is not a function
    at Object.useEvents (web-bd2fa8c7f7bc27342fd9031e1078bc53.js:1068:3606)
    at web-bd2fa8c7f7bc27342fd9031e1078bc53.js:1092:7918
...
```

**Comment by G-Ray** [comment] 2023-03-13 09:45
Unfortunately I'm unable to reproduce.
Do you use `npm` or `yarn` ?
Same issue with multiple browsers ?

**Comment by G-Ray** [comment] 2023-04-12 10:50
You might need to append `--clear` to your command line and retry @crloz

**Comment by jonnigg** [comment] 2023-05-25 23:47
> Steps to reproduce:
> 
> 1. `TAMAGUI_TARGET=web npx expo export --platform web`
> 2. npx serve dist
> 3. go to localhost:3000
> 
> ```
> TypeError: (0 , S.usePressability) is not a function
>     at Object.useEvents (web-bd2fa8c7f7bc27342fd9031e1078bc53.js:1068:3606)
>     at web-bd2fa8c7f7bc27342fd9031e1078bc53.js:1092:7918
> ...
> ```

@crloz did you ever find a fix for this? I am experiencing the same issue.

Thank you

**Comment by G-Ray** [comment] 2023-05-30 14:03
I can reproduce with `TAMAGUI_TARGET=native npx expo export --platform web --clear`.
But if I set the correct TAMAGUI_TARGET, with `--clear`: `TAMAGUI_TARGET=web npx expo export --platform web --clear`, it works on web.

Did your try appending `--clear` to your command line ?

**Comment by crloz** [comment] 2023-06-01 16:03
I pulled the latest changes & clean install.
It works ok.

thanks @G-Ray

**Closed as completed** 2023-06-04 22:39 UTC
